### ISSUE TITLE
Improve the channel collector.channels.gardian

### ISSUE THREAD

**Issue by vied12** [jplusplus/broken-promises#1]
- Needs to exclude some useless articles (see the `section` parameter)
- Filter articles retrieved because of the publication date
- Improve page parsing, remove javascript code from results

**Comment by paulloz** [comment]
> - [ ] Needs to exclude some useless articles (see the `section` parameter)
> - [x] Filter articles retrieved because of the publication date
> - [x] Improve page parsing, remove javascript code from results
