### ISSUE TITLE
Bug control tower: Je dois vider mon cache à chaque lancement de la tour de controle

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#11]
Sinon je ne vois que les articles que j'ai déjà noté.

**cache pas vidé** Je ne vois que les articles déjà notés
![cache-pas-vide](https://f.cloud.github.com/assets/2103603/1490873/05f5acd2-479f-11e3-9eba-eefcdcd71416.png)

**cache vidé** J'arrive au bout de la page et tous les articles, même ceux non notés
![cache-vide](https://f.cloud.github.com/assets/2103603/1490875/092602bc-479f-11e3-9396-0f108a79f895.png)

**Comment by annelisebouyer** [comment]
TU pourras le faire en prio steup ? C'est embetant !!

**Comment by vied12** [comment]
A tester, j'ai ajouté un timestamp à la requête

8edb5914861bda66dd34c48a0695f470a2e3aacf
