### ISSUE TITLE
Change text in "?" next to a date

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#13]
![capture decran 2013-11-18 a 17 44 00](https://f.cloud.github.com/assets/2103603/1564523/5ae512da-5070-11e3-8980-1aedd7b389b9.png)

Changer le texte à côté des dates:
This column shows articles in the Guardian archive mentioning November 18 2013.

PAR

**This column shows articles in the selected archive mentioning November 18 2013.**

et

This column show articles from 2012 or later mentioning 2013.

PAR

**This column shows articles mentioning 2013.**

**Comment by vied12** [comment]
Lui c'est le client :)
Allez tu vas y arriver !

**Comment by annelisebouyer** [comment]
J'ai bien assigné à Paulloz hein :)

On peut pas fusionner les 2 projets d'ailleurs ?

**Comment by vied12** [comment]
je l'avais suggéré mais @Pirhoo et @Paulloz préfère garder deux projets distincts.
L'avantage c'est de garder le collecteur et le client bien dissociés puisque le BE peut fonctionner sans FE. Surtout qu'ils utilisent des techno très différentes (BE: python/ FE: node.js)
L’inconvénient que je trouve c'est que le client à besoin de l'api du collecteur pour fonctionner... Il y a donc deux projets à installer et configurer si l'on veut le client.
