### ISSUE TITLE
API Guardian: Supprimer les références à la  <date recherchée> dans un commentaire embeddé

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#15]
Par exemple ici http://www.theguardian.com/politics/2013/nov/04/why-is-puberty-starting-younger-precocious

![capture decran 2013-11-18 a 18 03 36](https://f.cloud.github.com/assets/2103603/1564709/482624ba-5073-11e3-9e35-5865ffcc57ed.png)

Il s'agit du commentaire ici http://www.theguardian.com/politics/2013/nov/04/why-is-puberty-starting-younger-precocious?commentpage=1

Embeddé dans un de leur article

**Comment by vied12** [comment]
tu l'aimes bien dis donc cet article !

**Comment by vied12** [comment]
0824ff80c8160e3ef0e4fa9ae86e3ecd88205c42
