### ISSUE TITLE
Retourner la date du dernier scrap+nb de résultats pour chaque date

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#18]
Pour chaque date, on aurait besoin de récupérer la date du dernier scrap.
(ou un message si la date n'a jamais été scrapée)

Par exemple, en front cela donnerait ça:

![canevas_4](https://f.cloud.github.com/assets/2103603/1574455/68929ae6-513e-11e3-9204-109bd45f0148.png)

**Comment by vied12** [comment]
Ne pas oublier qu'il est possible d'avoir des résultats pour un date sans qu'elle ai été scrapée.
On peux trouver d'autres dates dans un document qui a été scrapé dans la recherche d'une autre date.

**Comment by annelisebouyer** [comment]
Oh bien vu merci ! J'avais pas du tout pensé à ce cas. Du coup je change le wording pour regrouper les cas
- pas scrappé et pas de résultats
- pas scrappé mais un/des résultats
- scrappé mais pas de résultats

je met à jour dans l'après-midi

**Comment by vied12** [comment]
Du coup il faudrait aussi pouvoir supprimer (ou évaluer) les dates individuellement depuis la Control Tower plutôt que le système actuel où on note l'article.

**Comment by annelisebouyer** [comment]
Non pas forcément on avoir automatiquement ces infos ? (date de scrapp, combien de résultats) ?

**Comment by vied12** [comment]
je veux dire que le système actuel de notation évalue que l'article. Alors qu'il peut contenir plusieurs dates, pertinentes ou non. Maintenant il faudrait pouvoir supprimer la référence d'une date, plus tout l''article comme c'est actuellement le cas.
vous pouvez répéter la question?

**Comment by vied12** [comment]
(ceci n'est pas en rapport avec ce thread mais une réflexion à propos ma première remarque.
https://github.com/jplusplus/broken-promises/issues/18#issuecomment-28890662

**Comment by annelisebouyer** [comment]
Hop du coup je t'ai listé les 3 cas possibles:

**pas scrappé et pas de résultats** 
![case1](https://f.cloud.github.com/assets/2103603/1593268/d776dd92-52c8-11e3-9e68-2af99f0fcc73.png)

**pas scrappé mais un ou plusieurs résultats**
![case2](https://f.cloud.github.com/assets/2103603/1593270/de7959ee-52c8-11e3-842a-b7930e2cd83b.png)

**scrappé (peu importe le nb de resultats)**
![case3](https://f.cloud.github.com/assets/2103603/1593271/e433803a-52c8-11e3-9327-5cae221495be.png)

Du coup on a besoin en front de récupérer les infos suivantes de ton côté:
- Date du dernier scrap (ou null)
- Nb de resultats

T'en penses quoi ? Si ça te plait je fais un 2eme ticket :)

**Comment by vied12** [comment]
Fait!

http://localhost:5000/last_scrape/2013/11/22

``` json
{
    "last_scrape_date": "2013-11-21T18:22:48",
    "last_scrape_results_count": 46,
    "searched_date": [
        2013,
        11,
        22
    ],
    "status": "ok"
}
```

http://localhost:5000/last_scrape/2013/11/11

``` json
{
    "searched_date": [
        2013,
        11,
        11
    ],
    "status": "no_result"
}
```

http://localhost:5000/count/2013/11/25

``` json
{
    "count": 3,
    "searched_date": [
        2013,
        11,
        25
    ],
    "status": "ok"
}
```
