### ISSUE TITLE
Implémenter le fait de pouvoir naviguer entre les dates

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#19]
A l'aide de flèches sur chaque board, l'utilisateur doit pouvoir naviguer dans chaque date (et choisir n'importe quelle date au format jour/mois/année).

On a 3 cas qu'on doit pouvoir détecter pour s'en servir côté front:
- Les articles à cette date ont bien été scrappés, ils sont affichés dans le board concerné
- La date a bien été scrappée mais cela n'a retourné aucun résultat
- La date n'a jamais été scrappée (trop ancienne ou trop dans le futur)

**Comment by vied12** [comment]
fixed with #18 ?
