### ISSUE TITLE
Implémenter le scrap automatique des dates : lesquelles et quand

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#20]
Coté back tu dois scrapper automatiquement, chaque jour les articles relatifs à :
- La date du jour
- Le mois en cours
- L'année en cours
- Les dates dans le futur qui sont au plus à jour J + 7  (et scrapper J+6, J+5, J+4 ....J+0).
  On a ainsi une vision d'une semaine d'avance

**Comment by vied12** [comment]
Done.
I scrap
- the current day and the next 6 days every day
- the current month and the next one twice a month
- the current year and the next one once a year

**Comment by vied12** [comment]
542afab5f66da155cf585fdff7771062e665fd90
