### ISSUE TITLE
Garder le style original des articles dans l'aperçu: Des erreurs

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#23]
J'ai l'impression que parfois le style n'est pas gardé à l'identique. Je n'ai pas encore trouvé tous les cas mais voici un exemple (http://www.theguardian.com/society/2013/sep/18/society-daily-email) :

**Ce qu'on voit**
![capture decran 2013-11-25 a 15 44 30](https://f.cloud.github.com/assets/2103603/1613788/b44be5b4-55df-11e3-8781-e9bc7f3427fe.png)

**Ce qu'on devrait voir** (Une liste de liens)
![capture decran 2013-11-25 a 15 44 36](https://f.cloud.github.com/assets/2103603/1613790/b80966fe-55df-11e3-80b6-0b688104748c.png)

**Comment by vied12** [comment]
b9784eafe1cc4c7864afeee76fe667e94fce598a
