### ISSUE TITLE
Ne pas envoyer de mail si il n'y a pas de nouveaux résultats

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#28]
Email apres suscribe:

Si apres avoir servi la requête de l'utilisateur il n'y a pas de nouveaux résultat, on ne doit pas envoyer le mail.

(pas de résultats ni dans la base ni dans le scrap demandé).

**Comment by annelisebouyer** [comment]
Je crois que ça marche pas j'ai testé avec le 2 et 3 décembre et il n'y a pas de nouveaux résultats apres le scrap à la demande. Pourtant je reçois quand meme le mail

**Comment by vied12** [comment]
Juste avant tu demande de ne pas envoyer "_si pas de résultats ni dans la base ni dans le scrap demandé_".

Pour le 2 et 3 Dec 2013, il y en a en bdd.

**Comment by annelisebouyer** [comment]
Ah oui sorry je voulais dire pas de nouveaux résultats entre avant le nouveau scrap et apres
