### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by joshuarrrr** [jplusplus/broken-promises#31]
I noticed that there's no longer any data available at http://brokenpromises.jplusplus.org/#/

Are there any current plans to update, maintain or refresh this project? I really like the idea, so I hope it's not abandoned.

**Comment by n-kb** [comment]
Hi @joshuarrrr, we pulled the plug on the workers that were pulling the data because server costs were too high. But you're welcome to fork and host it :)
