### ISSUE TITLE
API Guardian: Supprimer les références à la  <date recherchée> dans un tweet embeddé

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#8]
Par exemple ici http://www.theguardian.com/politics/2013/nov/04/why-is-puberty-starting-younger-precocious

**Comment by vied12** [comment]
semble être résolu par le ticket #9 , puisque les tweets ne sont jamais postérieurs à la date de publication.

**Comment by annelisebouyer** [comment]
Quid du cas où l'article serait édité (mis à jour) avec un tweet posterieur à la date de publication (mais donc antérieur à la date d'édition) ?

**Comment by vied12** [comment]
Si tu penses que ce n'est pas négligeable, je peux ajouter une règle.
Mais il me faudrait un exemple, dans ton lien c'est un commentaire, pas un tweet.

**Comment by annelisebouyer** [comment]
Ah oui c'est les commentaires du site du Guardian! 

Non je pense que c'est un cas qui peut-être certes rare mais arriver. Du coup il faut 2 tickets, un pour les comms un pour les tweets.

**Comment by annelisebouyer** [comment]
Hop par exemple ici ils ont embeddé plein de tweets

http://www.theguardian.com/business/2013/sep/18/greece-strike-markets-fed-tapering-live

**Comment by vied12** [comment]
0824ff80c8160e3ef0e4fa9ae86e3ecd88205c42
