### ISSUE TITLE
Général: ne pas retourner les articles si <date citée> <= <date de l'article>

### ISSUE THREAD

**Issue by annelisebouyer** [jplusplus/broken-promises#9]
Par exemple ici 

UK top 20 video games chart
http://www.theguardian.com/technology/2013/nov/04/top-20-video-games

date recherchée = November 2013
date citée = 2 November 2013
date de l'article = 4 November 2013

**Comment by annelisebouyer** [comment]
T'es sur que tu vérifie bien 
<date citée> <= <date de l'article>
et non pas
<date citée> < <date de l'article>

**Comment by vied12** [comment]
ce qui se passe :
je prends la date trouvée, 

``` python
date_trouvee = (2013, 11 None) # November 2013
```

Je la transforme pour donner une vrai date

``` python
date_transformee = datetime.date(
    date_trouvee[0], 
    date_trouvee[1] or 1, 
    date_trouvee[2] or 1)
# date_transformee  == datetime(2013, 11, 1) (1 November 2013)
```

Je la compare avec la date de publication pour les fitlrer:

``` python
if date_transformee >= date_publication:
    on_garde(date_transformee)
```

Donc en effet, c'est `<` et non `<=` si on inverse la comparaison.

Je la change donc!

**Comment by vied12** [comment]
Ah non je me referai au commit joint, mais depuis ça a changé : https://github.com/jplusplus/broken-promises/blob/master/Sources/brokenpromises/operations.py#L74

c'est bien comme tu voulais,

T'as un exemple où ça ne marche pas comme prévu ? Ou c'est juste une question plaisir ?

**Comment by annelisebouyer** [comment]
Ah mince j'avais bien un exemple mais je l'ai noté en -2 du coup et l'ai perdu.
Mais si le code le dit alors :)
